name: release

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      # Install npm versions
      - name: Install Dependencies
        run: npm install
      
      # run Dist
      - name: Build zips and test
        run: npm test
        
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./test-output/test-results.xml
      
      # Deploy ore-exchange
      - name: Set ore-exchange version
        run: echo "::set-output name=version::$(npm run --silent version-ore-exchange)"
        id: ore-exchange
      
      - uses: mukunku/tag-exists-action@v1.0.0
        id: ore-exchange-exists
        with: 
          tag: "ore_exchange-${{ steps.ore-exchange.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: "echo ${{ steps.ore-exchange-exists.outputs.exists }}"
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.ore-exchange-exists.outputs.exists == 'false'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "ore_exchange-${{ steps.ore-exchange.outputs.version }}"
          title: "Ore Exchange ${{ steps.ore-exchange.outputs.version }}"
          prerelease: false
          files: |
            dist/ore_exchange-${{ steps.ore-exchange.outputs.version }}.zip

      # Deploy bloomin-town
      - name: Set bloomin-town version
        run: echo "::set-output name=version::$(npm run --silent version-bloomin-town)"
        id: bloomin-town
      
      - uses: mukunku/tag-exists-action@v1.0.0
        id: bloomin-town-exists
        with: 
          tag: "bloomin_town-${{ steps.bloomin-town.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: "echo ${{ steps.bloomin-town-exists.outputs.exists }}"
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.bloomin-town-exists.outputs.exists == 'false'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "bloomin_town-${{ steps.bloomin-town.outputs.version }}"
          title: "Bloomin Town ${{ steps.bloomin-town.outputs.version }}"
          prerelease: false
          files: |
            dist/bloomin_town-${{ steps.bloomin-town.outputs.version }}.zip
            dist/bloomin_town_snapshot-${{ steps.bloomin-town.outputs.version }}.zip
