name: test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      # Install npm versions
      - name: Install Dependencies
        run: npm install
      
      # run Test
      - name: Run Tests
        run: npm test
      
      # Artifact the packs in case we want to manually test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-output/test-results.xml
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-output/test-results.xml